import React, { useState } from 'react';
import { 
  CheckCircle, 
  FileCheck, 
  Shield, 
  Smartphone, 
  Printer, 
  History, 
  FileText, 
  Download, 
  Menu, 
  X,
  ChevronRight,
  Database,
  Lock,
  Search,
  AlertTriangle,
  Play,
  ArrowRight
} from 'lucide-react';
import { Button } from './components/Button';
import { MockInterface } from './components/MockInterface';
import { PricingTier, FaqItem, LeadForm } from './types';

// --- Components ---

const Logo = ({ className = "w-9 h-9" }: { className?: string }) => (
  <img 
    src="immulogo.png" 
    alt="ImmuLog Logo" 
    className={`object-contain ${className}`} 
  />
);

// --- Data Constants ---

const PRICING_TIERS: PricingTier[] = [
  {
    name: 'Pilot Partner',
    price: 'Free',
    description: 'Forever-free status for our first 10 partners.',
    features: ['Up to 20 instruments', 'Direct Founder Access', 'Roadmap Influence', 'White-glove Onboarding'],
    cta: 'Secure Pilot Spot',
    popular: false
  },
  {
    name: 'Compliance',
    price: '$29',
    description: 'The standard for audit-ready labs.',
    features: ['Up to 50 instruments', 'Due-date Alerts', 'Full Audit Reports', 'Certificate Storage', 'Priority Support'],
    cta: 'Join Waitlist',
    popular: true
  },
  {
    name: 'Growth',
    price: '$79',
    description: 'For high-throughput facilities.',
    features: ['Up to 250 instruments', 'Multiple Locations', 'RBAC (Roles)', 'Bulk Import/Export', 'SLA Support'],
    cta: 'Request Access',
    popular: false
  }
];

const FAQS: FaqItem[] = [
  {
    question: "When can I start using ImmuLog?",
    answer: "We are currently onboarding our first batch of pilot labs (Stage 0). Join the waitlist today to secure your spot in the next cohort opening next week."
  },
  {
    question: "Will auditors accept these digital logs?",
    answer: "Yes. ImmuLog outputs reports designed specifically to meet ISO 17025 Section 7.5 (Technical Records). The reports automatically include the mandatory 'Who, When, What, and Result' data points, ensuring they cannot be rejected for lack of traceability."
  },
  {
    question: "How do you handle data integrity (ALCOA+)?",
    answer: "Our database is append-only. No records can be deleted. Corrections are handled via a 'Void & Re-enter' workflow that forces a user to input a reason for change, preserving the full audit trail."
  },
  {
    question: "Can I export my data if I cancel?",
    answer: "Yes. You own your data. You can export your full equipment registry (CSV) and all audit reports (PDF) at any time without restriction."
  }
];

// --- Sub-components ---

const AuditReportPreview = () => (
  <div className="relative group perspective-1000">
     {/* Abstract background elements */}
    <div className="absolute top-4 -right-4 w-full h-full bg-slate-800 rounded-sm border border-slate-700 opacity-50 transform rotate-2"></div>
    <div className="absolute top-2 -right-2 w-full h-full bg-slate-800 rounded-sm border border-slate-600 opacity-70 transform rotate-1"></div>
    
    {/* Main Paper */}
    <div className="relative bg-white w-full max-w-lg mx-auto h-[600px] shadow-2xl rounded-sm overflow-hidden flex flex-col transform transition-transform duration-500 hover:-translate-y-2">
      
      {/* Paper Header */}
      <div className="h-16 border-b-2 border-slate-900 mx-8 mt-8 flex justify-between items-end pb-2">
        <div className="flex items-center gap-2 text-slate-900">
          <Logo className="w-8 h-8" />
          <span className="font-bold tracking-tight text-lg">ImmuLog Audit Log</span>
        </div>
        <div className="text-right">
          <div className="text-[10px] uppercase tracking-widest text-slate-500 font-bold">Status</div>
          <div className="text-sm font-mono font-bold text-green-600">COMPLIANT</div>
        </div>
      </div>

      {/* Paper Body */}
      <div className="p-8 font-mono text-[10px] md:text-xs text-slate-600 leading-relaxed space-y-6">
        
        {/* Metadata Grid */}
        <div className="grid grid-cols-2 gap-4 bg-slate-50 p-4 border border-slate-100">
          <div>
            <span className="block text-slate-400 uppercase tracking-wider text-[9px] mb-1">Generated By</span>
            <span className="font-bold text-slate-800">Jane Doe (Lab Manager)</span>
          </div>
          <div>
            <span className="block text-slate-400 uppercase tracking-wider text-[9px] mb-1">Date Range</span>
            <span className="font-bold text-slate-800">2023-01-01 — 2023-10-01</span>
          </div>
          <div>
            <span className="block text-slate-400 uppercase tracking-wider text-[9px] mb-1">Scope</span>
            <span className="font-bold text-slate-800">All Instruments (Active)</span>
          </div>
          <div>
            <span className="block text-slate-400 uppercase tracking-wider text-[9px] mb-1">Report ID</span>
            <span className="font-bold text-slate-800">IM-8921-X99</span>
          </div>
        </div>

        {/* Table */}
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b-2 border-slate-200 text-slate-400 uppercase text-[9px] tracking-wider">
              <th className="py-2 pl-2">Date</th>
              <th className="py-2">Asset ID</th>
              <th className="py-2">Technician</th>
              <th className="py-2 text-right pr-2">Outcome</th>
            </tr>
          </thead>
          <tbody className="text-slate-700">
            <tr className="border-b border-slate-100 hover:bg-yellow-50">
              <td className="py-3 pl-2">2023-09-12</td>
              <td className="font-bold">PIP-004</td>
              <td>J. Doe</td>
              <td className="text-right pr-2"><span className="bg-green-100 text-green-800 px-1.5 py-0.5 rounded text-[9px] font-bold border border-green-200">PASS</span></td>
            </tr>
            
            {/* VOID Entry */}
            <tr className="bg-slate-50 border-b border-slate-100 text-slate-400 line-through decoration-red-400">
              <td className="py-3 pl-2">2023-09-15</td>
              <td className="font-bold">BAL-102</td>
              <td>S. Smith</td>
              <td className="text-right pr-2"><span className="bg-red-100 text-red-800 px-1.5 py-0.5 rounded text-[9px] font-bold border border-red-200 no-underline inline-block">VOID</span></td>
            </tr>
            
             <tr className="border-b border-slate-100 hover:bg-yellow-50">
              <td className="py-3 pl-2">2023-09-15</td>
              <td className="font-bold">BAL-102</td>
              <td>S. Smith</td>
              <td className="text-right pr-2"><span className="bg-green-100 text-green-800 px-1.5 py-0.5 rounded text-[9px] font-bold border border-green-200">PASS</span></td>
            </tr>
            <tr className="border-b border-slate-100 hover:bg-yellow-50">
              <td className="py-3 pl-2">2023-10-01</td>
              <td className="font-bold">CENT-01</td>
              <td>A. Wong</td>
              <td className="text-right pr-2"><span className="bg-green-100 text-green-800 px-1.5 py-0.5 rounded text-[9px] font-bold border border-green-200">PASS</span></td>
            </tr>
          </tbody>
        </table>
        
        {/* Footer Seal */}
        <div className="absolute bottom-8 left-8 right-8 flex items-center gap-4 border-t border-slate-100 pt-4">
           <div className="w-12 h-12 border-2 border-slate-200 rounded-full flex items-center justify-center">
             <Shield size={20} className="text-slate-300" />
           </div>
           <div className="text-[9px] text-slate-400">
             <p>Electronically Generated by ImmuLog</p>
             <p>Immutable Record • ISO 17025 Compliant Format</p>
           </div>
        </div>
      </div>
    </div>
  </div>
);

// --- Main Page Component ---

function App() {
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [formState, setFormState] = useState<LeadForm>({
    email: '',
    labType: '',
    standard: '',
    instrumentCount: '',
    painPoint: ''
  });

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
    setFormState({
      ...formState,
      [e.target.name]: e.target.value
    });
  };

  const handleFormSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    alert("Thanks for joining the pilot! We'll be in touch shortly.");
  };

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
    setIsMobileMenuOpen(false);
  };

  return (
    <div className="min-h-screen bg-white text-slate-900 font-sans selection:bg-blue-100 selection:text-blue-900">
      
      {/* Technical Grid Background */}
      <div className="fixed inset-0 pointer-events-none z-0 opacity-[0.03]" 
           style={{ backgroundImage: 'linear-gradient(#0f172a 1px, transparent 1px), linear-gradient(to right, #0f172a 1px, transparent 1px)', backgroundSize: '40px 40px' }}>
      </div>

      {/* 0. Sticky Top Bar */}
      <nav className="sticky top-0 z-50 bg-white/90 backdrop-blur-md border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16 items-center">
            {/* Logo */}
            <div className="flex items-center gap-2 cursor-pointer group" onClick={() => window.scrollTo(0, 0)}>
              <Logo />
              <span className="font-bold text-xl tracking-tight text-slate-900">ImmuLog</span>
            </div>

            {/* Desktop Nav */}
            <div className="hidden md:flex items-center gap-6">
              <button onClick={() => scrollToSection('features')} className="text-sm font-medium text-slate-600 hover:text-slate-900 transition-colors">Features</button>
              <button onClick={() => scrollToSection('pricing')} className="text-sm font-medium text-slate-600 hover:text-slate-900 transition-colors">Pricing</button>
              <div className="h-4 w-px bg-slate-300"></div>
              <Button size="sm" variant="secondary" onClick={() => scrollToSection('pilot')}>Book Demo</Button>
              <Button size="sm" onClick={() => scrollToSection('pilot')}>Join Pilot</Button>
            </div>

            {/* Mobile Menu Button */}
            <div className="md:hidden">
              <button onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)} className="text-slate-600">
                {isMobileMenuOpen ? <X /> : <Menu />}
              </button>
            </div>
          </div>
        </div>

        {/* Mobile Nav */}
        {isMobileMenuOpen && (
          <div className="md:hidden bg-white border-b border-slate-200 px-4 py-4 space-y-4 shadow-lg absolute w-full">
            <button onClick={() => scrollToSection('features')} className="block w-full text-left font-medium text-slate-700">Features</button>
            <button onClick={() => scrollToSection('pricing')} className="block w-full text-left font-medium text-slate-700">Pricing</button>
            <Button fullWidth onClick={() => scrollToSection('pilot')}>Join Pilot</Button>
          </div>
        )}
      </nav>

      {/* 1. Hero Section */}
      <section className="relative pt-12 pb-20 lg:pt-24 lg:pb-32 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="space-y-8 text-center lg:text-left">
              
              {/* Badge */}
              <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 border border-blue-100 text-blue-700 text-xs font-semibold uppercase tracking-wide mx-auto lg:mx-0">
                <Shield size={12} />
                <span>ISO 17025 Traceability</span>
              </div>

              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight text-slate-900 leading-[1.1]">
                ISO 17025 Compliance.<br/>
                <span className="text-blue-600 relative inline-block">Zero Binders.
                  <svg className="absolute w-full h-3 -bottom-1 left-0 text-blue-200 -z-10" viewBox="0 0 100 10" preserveAspectRatio="none"><path d="M0 5 Q 50 10 100 5" stroke="currentColor" strokeWidth="8" fill="none" /></svg>
                </span>
              </h1>
              <p className="text-lg sm:text-xl text-slate-600 max-w-2xl mx-auto lg:mx-0 leading-relaxed">
                ImmuLog replaces risky Excel sheets and paper logs with a <span className="font-semibold text-slate-900">secure, immutable, and audit-ready</span> digital registry.
              </p>
              
              <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                <Button size="lg" onClick={() => scrollToSection('pilot')} className="gap-2 shadow-blue-500/25">
                  Join Pilot Waitlist <ArrowRight size={18} />
                </Button>
                <Button size="lg" variant="secondary" className="gap-2">
                  <Play size={18} fill="currentColor" className="text-slate-400" /> Watch 45s Demo
                </Button>
              </div>

              {/* Trust Chips */}
              <div className="pt-6 border-t border-slate-100 flex flex-wrap justify-center lg:justify-start gap-x-8 gap-y-4 text-sm font-medium text-slate-500">
                <div className="flex items-center gap-2"><CheckCircle size={16} className="text-green-500" /> ALCOA+ Aligned</div>
                <div className="flex items-center gap-2"><CheckCircle size={16} className="text-green-500" /> Void-Safe Audit Trail</div>
                <div className="flex items-center gap-2"><CheckCircle size={16} className="text-green-500" /> Instant Retrieval</div>
              </div>
            </div>

            {/* Hero Visual */}
            <div className="relative flex justify-center lg:justify-end">
              <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] bg-blue-100 rounded-full blur-[100px] -z-10 opacity-60"></div>
              <MockInterface />
            </div>
          </div>
        </div>
      </section>

      {/* 2. The Problem */}
      <section className="py-20 bg-slate-50 border-y border-slate-200">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-xs font-bold text-slate-500 uppercase tracking-widest mb-3">Risk Management</h2>
          <h3 className="text-3xl font-bold text-slate-900 mb-12">The hidden cost of "Good Enough."</h3>
          
          <div className="grid md:grid-cols-3 gap-6 text-left">
            {/* Card 1: Search */}
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 hover:border-red-200 transition-colors group">
              <div className="w-10 h-10 bg-slate-100 rounded-lg flex items-center justify-center mb-4 group-hover:bg-red-50 transition-colors">
                <Search className="text-slate-600 group-hover:text-red-500" size={20} />
              </div>
              <h4 className="font-bold text-slate-900 mb-2">Retrieval Delays</h4>
              <p className="text-slate-600 text-sm leading-relaxed">Auditors interpret delay as disorganization. Finding a 2022 cert in a shared drive shouldn't take 45 minutes.</p>
            </div>
            
            {/* Card 2: Excel */}
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 hover:border-orange-200 transition-colors group">
              <div className="w-10 h-10 bg-slate-100 rounded-lg flex items-center justify-center mb-4 group-hover:bg-orange-50 transition-colors">
                <AlertTriangle className="text-slate-600 group-hover:text-orange-500" size={20} />
              </div>
              <h4 className="font-bold text-slate-900 mb-2">Data Integrity Risks</h4>
              <p className="text-slate-600 text-sm leading-relaxed">Excel cells are not immutable. Overwritten dates or deleted rows are a major red flag for data integrity audits.</p>
            </div>

            {/* Card 3: LIMS */}
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 hover:border-blue-200 transition-colors group">
              <div className="w-10 h-10 bg-slate-100 rounded-lg flex items-center justify-center mb-4 group-hover:bg-blue-50 transition-colors">
                <Database className="text-slate-600 group-hover:text-blue-500" size={20} />
              </div>
              <h4 className="font-bold text-slate-900 mb-2">Validation Fatigue</h4>
              <p className="text-slate-600 text-sm leading-relaxed">Full LIMS suites require massive validation packages (IQ/OQ/PQ). ImmuLog offers a lightweight, focused alternative.</p>
            </div>
          </div>

          <div className="mt-12 bg-white inline-block px-8 py-4 rounded-full border border-slate-200 shadow-sm">
            <p className="text-lg font-medium text-slate-800">
              "ImmuLog is the precise tool for calibration history. <span className="text-blue-600 font-bold">No bloat. Just compliance.</span>"
            </p>
          </div>
        </div>
      </section>

      {/* 3. How It Works */}
      <section id="features" className="py-24 bg-white relative">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900">Compliance in 4 Steps</h2>
            <p className="text-slate-500 mt-2">Designed for the lab floor, validated for the auditor.</p>
          </div>

          <div className="grid md:grid-cols-4 gap-6">
            {[
              { icon: Database, title: "1. Registry", desc: "Centralize ID, serials, and calibration intervals.", color: "text-blue-600" },
              { icon: Printer, title: "2. Tag Assets", desc: "Generate unique QR labels for every instrument.", color: "text-teal-600" },
              { icon: Smartphone, title: "3. Scan to Log", desc: "Technicians scan & upload certs at the bench.", color: "text-indigo-600" },
              { icon: Download, title: "4. Audit Export", desc: "Retrieve full history by date range instantly.", color: "text-purple-600" }
            ].map((step, idx) => (
              <div key={idx} className="relative p-6 bg-slate-50 rounded-xl border border-slate-100 hover:shadow-lg transition-shadow duration-300">
                <div className={`mb-4 ${step.color}`}>
                   <step.icon size={32} strokeWidth={1.5} />
                </div>
                <h3 className="text-slate-900 font-bold text-lg mb-2">{step.title}</h3>
                <p className="text-slate-600 text-sm leading-relaxed">{step.desc}</p>
                {idx < 3 && <div className="hidden md:block absolute top-1/2 -right-3 transform -translate-y-1/2 text-slate-300 z-10">
                   <ChevronRight />
                </div>}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 4. The Audit Button */}
      <section className="py-24 bg-slate-900 text-white overflow-hidden relative">
        {/* Background Grid for Technical Feel */}
        <div className="absolute inset-0 opacity-[0.05]" 
             style={{ backgroundImage: 'linear-gradient(#ffffff 1px, transparent 1px), linear-gradient(to right, #ffffff 1px, transparent 1px)', backgroundSize: '24px 24px' }}>
        </div>
        
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="grid lg:grid-cols-2 gap-16 items-center">
            <div>
              <div className="inline-block px-3 py-1 rounded bg-blue-900/50 border border-blue-700 text-blue-300 text-[10px] font-mono font-bold uppercase tracking-widest mb-6">
                Audit Defense
              </div>
              <h2 className="text-3xl lg:text-4xl font-bold mb-6 leading-tight">The Audit Button: <br/>Proof in one click.</h2>
              <p className="text-slate-300 text-lg mb-8 leading-relaxed font-light">
                Generate an auditor-ready PDF by date range, instrument, location, or technician. Designed to meet <strong className="text-white">ISO 17025 Section 7.5 (Technical Records)</strong> requirements.
              </p>
              
              <ul className="space-y-4 mb-8">
                {[
                  "Traceable Metadata (ID, Serial, Location)",
                  "Immutable timestamped log entries",
                  "Direct links to original certificates",
                  "Void trail (Original + Reason + Replacement)"
                ].map((item, i) => (
                  <li key={i} className="flex items-center gap-3 text-slate-200">
                    <div className="bg-green-500/10 p-1 rounded-full">
                      <CheckCircle className="text-green-400 shrink-0" size={16} />
                    </div>
                    <span className="text-sm font-medium">{item}</span>
                  </li>
                ))}
              </ul>

              <Button 
                variant="primary" 
                size="lg" 
                className="font-bold"
                onClick={() => scrollToSection('pilot')}
              >
                Get Sample Report (Pilot)
              </Button>
            </div>
            
            <div className="relative">
              <AuditReportPreview />
            </div>
          </div>
        </div>
      </section>

      {/* 5. Compliance / Why Auditors Like It */}
      <section className="py-24 bg-white">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl font-bold text-slate-900 mb-4">Built for ALCOA+ Principles</h2>
          <p className="text-slate-500 mb-12 max-w-2xl mx-auto">We prioritized data integrity features that auditors check for first.</p>
          
          <div className="grid sm:grid-cols-2 gap-8 text-left">
            <div className="flex gap-4 p-4 rounded-lg hover:bg-slate-50 transition-colors">
              <div className="bg-blue-100 p-3 rounded-lg h-fit text-blue-700">
                <Lock size={24} />
              </div>
              <div>
                <h4 className="font-bold text-slate-900">Attributable & Legible</h4>
                <p className="text-sm text-slate-600 mt-1 leading-relaxed">Every action is tied to a unique user ID and timestamp. No anonymous edits.</p>
              </div>
            </div>
            <div className="flex gap-4 p-4 rounded-lg hover:bg-slate-50 transition-colors">
              <div className="bg-blue-100 p-3 rounded-lg h-fit text-blue-700">
                <History size={24} />
              </div>
              <div>
                <h4 className="font-bold text-slate-900">Original & Accurate</h4>
                <p className="text-sm text-slate-600 mt-1 leading-relaxed">Original records are preserved. Corrections require a reason code (audit trail).</p>
              </div>
            </div>
            <div className="flex gap-4 p-4 rounded-lg hover:bg-slate-50 transition-colors">
              <div className="bg-blue-100 p-3 rounded-lg h-fit text-blue-700">
                <FileCheck size={24} />
              </div>
              <div>
                <h4 className="font-bold text-slate-900">Contemporaneous</h4>
                <p className="text-sm text-slate-600 mt-1 leading-relaxed">Mobile scanning encourages logging at the time of calibration, not batch-entering later.</p>
              </div>
            </div>
            <div className="flex gap-4 p-4 rounded-lg hover:bg-slate-50 transition-colors">
              <div className="bg-blue-100 p-3 rounded-lg h-fit text-blue-700">
                <Download size={24} />
              </div>
              <div>
                <h4 className="font-bold text-slate-900">Available</h4>
                <p className="text-sm text-slate-600 mt-1 leading-relaxed">Records are retrievable throughout the data lifecycle, independent of staff turnover.</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 6. Who It's For */}
      <section className="py-20 bg-slate-50 border-t border-slate-200">
         <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
           <div className="grid md:grid-cols-2 gap-12">
             <div className="bg-white p-8 rounded-xl shadow-sm border border-slate-200">
               <h3 className="text-xl font-bold text-slate-900 mb-6 flex items-center gap-2">
                 <CheckCircle className="text-green-500 fill-green-100" /> Ideal For
               </h3>
               <ul className="space-y-4 text-slate-600">
                 <li className="flex gap-2 items-start"><span className="text-green-500 font-bold">✓</span> ISO 17025 Accredited Labs</li>
                 <li className="flex gap-2 items-start"><span className="text-green-500 font-bold">✓</span> GLP/GMP Environments (Non-Validation)</li>
                 <li className="flex gap-2 items-start"><span className="text-green-500 font-bold">✓</span> Biotech Startups (Seed to Series B)</li>
                 <li className="flex gap-2 items-start"><span className="text-green-500 font-bold">✓</span> University Core Facilities</li>
               </ul>
             </div>
             <div className="bg-slate-100 p-8 rounded-xl border border-slate-200 opacity-75 grayscale hover:grayscale-0 transition-all duration-500">
               <h3 className="text-xl font-bold text-slate-500 mb-6 flex items-center gap-2">
                 <X className="text-slate-400" /> Out of Scope
               </h3>
               <ul className="space-y-4 text-slate-500">
                 <li className="flex gap-2 items-start"><span>•</span> Enterprise Pharma (Requires 21 CFR Part 11 Validation Pkg)</li>
                 <li className="flex gap-2 items-start"><span>•</span> Supply Chain / Inventory Management</li>
                 <li className="flex gap-2 items-start"><span>•</span> Clinical Patient Data (HIPAA)</li>
               </ul>
             </div>
           </div>
         </div>
      </section>

      {/* 7. Pricing */}
      <section id="pricing" className="py-24 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-slate-900">Early Access Pricing</h2>
            <p className="text-slate-600 mt-4">Secure founder pricing by joining the pilot today.</p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
            {PRICING_TIERS.map((tier, idx) => (
              <div key={idx} className={`relative flex flex-col p-8 bg-white border rounded-2xl transition-transform duration-300 hover:-translate-y-1 ${tier.popular ? 'border-blue-600 shadow-xl z-10' : 'border-slate-200 shadow-sm'}`}>
                {tier.popular && (
                  <div className="absolute top-0 left-1/2 transform -translate-x-1/2 -translate-y-1/2 bg-blue-600 text-white text-[10px] font-bold uppercase tracking-wide px-3 py-1 rounded-full shadow-lg">
                    Recommended
                  </div>
                )}
                <h3 className="text-lg font-bold text-slate-900">{tier.name}</h3>
                <div className="mt-4 mb-2 flex items-baseline gap-1">
                  <span className="text-4xl font-extrabold text-slate-900 tracking-tight">{tier.price}</span>
                  <span className="text-slate-500 text-sm font-medium">/month</span>
                </div>
                <p className="text-slate-500 text-sm mb-6 pb-6 border-b border-slate-100">{tier.description}</p>
                <ul className="space-y-4 mb-8 flex-1">
                  {tier.features.map((feature, fIdx) => (
                    <li key={fIdx} className="flex items-start gap-3 text-sm text-slate-700">
                      <CheckCircle className="text-blue-500 shrink-0 mt-0.5" size={14} />
                      {feature}
                    </li>
                  ))}
                </ul>
                <Button 
                  variant={tier.popular ? 'primary' : 'secondary'} 
                  fullWidth
                  onClick={() => scrollToSection('pilot')}
                >
                  {tier.cta}
                </Button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 8. FAQ */}
      <section className="py-20 bg-slate-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-slate-900 text-center mb-12">Technical & Compliance FAQ</h2>
          <div className="grid gap-6">
            {FAQS.map((faq, idx) => (
              <div key={idx} className="bg-white p-6 rounded-lg shadow-sm border border-slate-200 hover:border-blue-200 transition-colors">
                <h3 className="text-lg font-bold text-slate-900 mb-2">{faq.question}</h3>
                <p className="text-slate-600 leading-relaxed text-sm">{faq.answer}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 9. Final CTA & Form */}
      <section id="pilot" className="py-24 bg-slate-900 text-white relative overflow-hidden">
        {/* Decorative Circles */}
        <div className="absolute top-0 right-0 -mr-20 -mt-20 w-96 h-96 bg-blue-600 rounded-full blur-3xl opacity-20"></div>
        <div className="absolute bottom-0 left-0 -ml-20 -mb-20 w-96 h-96 bg-purple-600 rounded-full blur-3xl opacity-20"></div>

        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center relative z-10">
          <h2 className="text-3xl md:text-5xl font-bold mb-6 tracking-tight">Secure your pilot spot.</h2>
          <p className="text-slate-300 mb-12 text-lg">Join the pilot to get founder pricing and secure your peace of mind before the next audit.</p>
          
          <form onSubmit={handleFormSubmit} className="max-w-lg mx-auto bg-white/5 backdrop-blur-lg p-8 rounded-2xl shadow-2xl border border-white/10 text-left">
            <div className="space-y-5">
              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Work Email</label>
                <input 
                  type="email" 
                  name="email"
                  required
                  placeholder="you@lab.com"
                  className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-600 text-white placeholder-slate-500 focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
                  value={formState.email}
                  onChange={handleInputChange}
                />
              </div>
              
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1">Lab Type</label>
                  <select 
                    name="labType"
                    className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-600 text-white focus:ring-2 focus:ring-blue-500 outline-none appearance-none"
                    value={formState.labType}
                    onChange={handleInputChange}
                  >
                    <option value="" className="bg-slate-800">Select...</option>
                    <option value="Biotech" className="bg-slate-800">Biotech</option>
                    <option value="Academic" className="bg-slate-800">Academic</option>
                    <option value="Contract" className="bg-slate-800">Contract Testing</option>
                    <option value="Manufacturing" className="bg-slate-800">Manufacturing</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-1"># Instruments</label>
                  <select 
                    name="instrumentCount"
                    className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-600 text-white focus:ring-2 focus:ring-blue-500 outline-none appearance-none"
                    value={formState.instrumentCount}
                    onChange={handleInputChange}
                  >
                    <option value="" className="bg-slate-800">Select...</option>
                    <option value="1-20" className="bg-slate-800">1-20</option>
                    <option value="21-50" className="bg-slate-800">21-50</option>
                    <option value="51-200" className="bg-slate-800">51-200</option>
                    <option value="200+" className="bg-slate-800">200+</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-slate-300 mb-1">Biggest Pain Point</label>
                <input 
                  type="text" 
                  name="painPoint"
                  placeholder="e.g. Lost binders, Excel errors..."
                  className="w-full px-4 py-3 rounded-lg bg-slate-900/50 border border-slate-600 text-white placeholder-slate-500 focus:ring-2 focus:ring-blue-500 outline-none"
                  value={formState.painPoint}
                  onChange={handleInputChange}
                />
              </div>

              <Button type="submit" size="lg" fullWidth className="mt-4 bg-blue-600 hover:bg-blue-500 text-white font-bold py-4">
                Join Pilot Waitlist
              </Button>
              <p className="text-xs text-center text-slate-500 mt-4">
                We respect your inbox. No spam.
              </p>
            </div>
          </form>
        </div>
      </section>

      {/* 10. Footer */}
      <footer className="bg-white border-t border-slate-200 py-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row justify-between items-center gap-6">
          <div className="flex items-center gap-2">
             <Logo className="w-6 h-6 text-slate-900" />
            <span className="font-bold text-slate-900 tracking-tight">ImmuLog</span>
          </div>
          
          <div className="flex flex-wrap justify-center gap-8 text-sm text-slate-600 font-medium">
            <a href="#" className="hover:text-blue-600 transition-colors">Contact</a>
            <a href="#" className="hover:text-blue-600 transition-colors">Privacy Policy</a>
            <a href="#" className="hover:text-blue-600 transition-colors">Terms of Service</a>
          </div>

          <div className="text-xs text-slate-400">
            © {new Date().getFullYear()} ImmuLog Inc. Data retained securely in the US.
          </div>
        </div>
      </footer>
    </div>
  );
}

export default App;